import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alf' at '27/08/15 13:20' with Gradle 2.5-rc-2
 *
 * @author alf, @date 27/08/15 13:20
 */
public class Library {
  private static final Logger LOG = LoggerFactory.getLogger(Library.class);

  public boolean someLibraryMethod() {
    LOG.info("Log initialized");
    return true;
  }
}
