import static org.junit.Assert.assertTrue;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'alf' at '27/08/15 13:20' with Gradle 2.5-rc-2
 *
 * @author alf, @date 27/08/15 13:20
 */
public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
